#!/bin/bash -vx

printenv | sort
echo '================'

TAG_NAME="dev"
DEST_IMAGE_NAME=$(basename $PWD)
DEST_IMAGE=docker.io/fermilabqc/${DEST_IMAGE_NAME}:${TAG_NAME}

if [ "$DOCKER_TAG" == "$TAG_NAME" ]
then
	docker tag $IMAGE_NAME $DEST_IMAGE
	docker push $DEST_IMAGE
fi
